### ISSUE TITLE
Register?

### ISSUE THREAD

**Issue by oxinabox** [SciML/PubChem.jl#15]
This package seems really cool.
It would be nice if it was registered.

**Comment by oxinabox** [comment]
ok.
@isaacsas what is actually required to release this?
I think it is ship-shaped now.

 - Working with current versions of ecosystem
 - using standard SciML CI
 - Giving nice errors
 
We can always release a v2.0.0 later

**Comment by isaacsas** [comment]
I'm fine with registering it. I guess we probably need to add keys for the various CI components to work?

**Comment by isaacsas** [comment]
I see tons of compat helper branches but none actually resulted in PRs, so something is messed up there.

**Comment by oxinabox** [comment]
I have no idea about that.
I personally don't use compat helper that often.
And on this repo I don't have permissions to do stuff with keys

**Comment by isaacsas** [comment]
I think tagbot should be straightened out too, so hopefully the tags will go through OK when it is merged.
