### ISSUE TITLE
Make compatible with Catalyst v14

### ISSUE THREAD

**Issue by oxinabox** [SciML/PubChem.jl#16]
Currently package is compatible with Catalyst v13
I am not sure what would be required for Catalyst v14 support but i suspect not much.

```
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Catalyst [479239e8]:
 Catalyst [479239e8] log:
 ├─possible versions are: 5.0.0-14.4.0 or uninstalled
 ├─restricted to versions 13 by PubChem [1db272ca], leaving only versions: 13.0.0-13.5.1
 │ └─PubChem [1db272ca] log:
 │   ├─possible versions are: 0.1.0 or uninstalled
 │   └─PubChem [1db272ca] is fixed to version 0.1.0
 └─restricted to versions 14.3.1-14 by POC_kinetic [349f8009] — no versions left
   └─POC_kinetic [349f8009] log:
     ├─possible versions are: 0.1.0 or uninstalled
     └─POC_kinetic [349f8009] is fixed to version 0.1.0
```

**Comment by isaacsas** [comment]
The package may need updates. This was a summer GSOC project that was never really completed/released unfortunately, and so needs someone to go through and handle updating / checking correctness for it, and then setting it up as a registered package. If this is of interest to you, help would certainly be appreciated as I don't think anyone else has this on their radar to update at this point in time.
